[server]
enableXsrfProtection = false
enableCORS = false

[auth]
enable = true
provider = "google"
client_id = "7094981523-9c3n63r3dqolj3fkgo5nd64dg6jt40c2.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "http://localhost:8501/oauth2callback"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
cookie_secret = "e7f82a9d79e4c04bba7483cf0cc10a6b182ef6a48a97f12cd0bd257a211c5fae"

[auth.google]
client_id = "7094981523-9c3n63r3dqolj3fkgo5nd64dg6jt40c2.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"