[server]
enableXsrfProtection = false
enableCORS = false

[auth]
enable = true
provider = "google"
client_id = "338885789570-8a6g1mlcrk3bkufaguf5d9ijn9ra9mmh.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "http://localhost:8501/auth/callback"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
cookie_secret = "e7f82a9d79e4c04bba7483cf0cc10a6b182ef6a48a97f12cd0bd257a211c5fae"

[auth.google]
client_id = "338885789570-8a6g1mlcrk3bkufaguf5d9ijn9ra9mmh.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
